import {
  BookOpen,
  BadgeCheck,
  BarChart3,
  Brain,
  Briefcase,
  Calculator,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Code,
  Compass,
  Factory,
  Feather,
  FilePen,
  FileText,
  FlaskConical,
  FolderOpen,
  Gavel,
  GraduationCap,
  Headset,
  HeartHandshake,
  HelpCircle,
  Info,
  LayoutGrid,
  Leaf,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Microscope,
  MessageSquare,
  PenTool,
  Presentation,
  Quote,
  Receipt,
  RefreshCcw,
  Route,
  SatelliteDish,
  Sparkles,
  TrendingUp,
  ThumbsUp,
  UserPlus,
  Users,
  XCircle,
} from "lucide-react";
import type { ComponentProps } from "react";
import type { LucideIcon } from "lucide-react";

export const materialToLucide: Record<string, LucideIcon> = {
  school: GraduationCap,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  verified_users: BadgeCheck,
  menu_book: BookOpen,
  auto_stories: BookOpen,
  edit_note: FilePen,
  functions: Calculator,
  business_center: Briefcase,
  group_add: UserPlus,
  receipt_long: Receipt,
  task_alt: ListChecks,
  request_quote: FileText,
  chat: MessageSquare,
  replay: RefreshCcw,
  lock: Lock,
  assignment: ClipboardList,
  format_quote: Quote,
  folder_open: FolderOpen,
  slideshow: Presentation,
  code: Code,
  bar_chart: BarChart3,
  calculate: Calculator,
  biotech: Microscope,
  science: FlaskConical,
  settings_input_antenna: SatelliteDish,
  precision_manufacturing: Factory,
  psychology_alt: Brain,
  psychology: Brain,
  trending_up: TrendingUp,
  history_edu: Feather,
  groups: Users,
  diversity_3: Users,
  eco: Leaf,
  info: Info,
  route: Route,
  emoji_objects: Lightbulb,
  volunteer_activism: HeartHandshake,
  help: HelpCircle,
  support_agent: Headset,
  check_circle: CheckCircle2,
  expand_more: ChevronDown,
  error: XCircle,
  thumb_up: ThumbsUp,
  category: LayoutGrid,
  forum: MessageSquare,
  handshake: HeartHandshake,
  tips_and_updates: Sparkles,
  travel_explore: Compass,
  design_services: PenTool,
  gavel: Gavel,
  mail: Mail,
};

export function MaterialIcon({
  name,
  size = 20,
  className,
  ...rest
}: {
  name: string;
  size?: number;
  className?: string;
} & Omit<ComponentProps<LucideIcon>, "size" | "className">) {
  const Icon = materialToLucide[name] ?? HelpCircle;
  return <Icon size={size} className={className} aria-hidden="true" {...rest} />;
}